sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '51251'
  mfg: 19/09/25
  exp: 19/09/28
system:
  ocrEngine: tesseract
  delayShutter: 50
  delayBeforeReject: 500
  rejectionPeriod: 100
  numberStickerBeforeDetection: 4
  rotateImage: 0
  detectionPercentage: 0
  detectionResizeImage: 70
  saveImage: false
hardware:
  camera:
    ExposureTime: 70000
    AnalogueGain: 3.04
    Brightness: -0.47000000000000003
    Contrast: 1.67
    Saturation: 2.66
    Sharpness: 4.08
    FrameRate: 25
  gpio:
    LED0: 20
    LED1: 21
    BUZZER: 19
    DI0: 22
    DI1: 27
    DO0: 23
    DO1: 24
    L0: 12
    L1: 23
  rectangle:
    x1: 300
    x2: 816
    y1: 198
    y2: 493
counters:
  ok: 0
  ng: 0
