sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '51251'
  mfg: 19/09/25
  exp: 19/09/28
system:
  ocrEngine: tesseract
  tesseractModel: label
  delayShutter: 50
  delayBeforeReject: 500
  rejectionPeriod: 100
  numberStickerBeforeDetection: 4
  rotateImage: 0
  detectionPercentage: 0
  detectionResizeImage: 100
  saveImage: false
preprocessor_settings:
  useAdaptiveThreshold: false
  useClahe: true
  useMorphologicalOpen: true
  useOtsuThreshold: true
  useSharpen: true
hardware:
  camera:
    ExposureTime: 800
    AnalogueGain: 4.39
    Brightness: 0.51
    Contrast: 2.06
    Saturation: 1.0
    Sharpness: 1.0
    FrameRate: 25
  gpio:
    TriggeredCamera: 25
    TriggeredReject: 26
    RejectOutput: 24
    Output1: 23
    Output2: 22
  rectangle:
    x1: 315
    x2: 690
    y1: 291
    y2: 524
counters:
  ok: 0
  ng: 0
