sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '12358'
  mfg: 01/05/25
  exp: 01/05/27
hardware:
  camera:
    zoom: 100
    focus: 170
    autoFocus: true
    brightness: 184
    contrast: 188
    exposure: 188
    sensorDelay: 500
    saveImage: false
  gpio:
    LED0: 20
    LED1: 21
    BUZZER: 19
    DI0: 22
    DI1: 27
    DO0: 23
    DO1: 24
    L0: 12
    L1: 23
  rectangle:
    x1: 562
    x2: 936
    y1: 250
    y2: 608
counters:
  ok: 0
  ng: 6
