sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '51251'
  mfg: 19/09/25
  exp: 19/09/28
system:
  ocrEngine: tesseract
  tesseractModel: label
  delayShutter: 50
  delayBeforeReject: 500
  rejectionPeriod: 100
  numberStickerBeforeDetection: 4
  rotateImage: 0
  detectionPercentage: 0
  detectionResizeImage: 100
  saveImage: false
preprocessor_settings:
  useAdaptiveThreshold: false
  useClahe: true
  useMorphologicalOpen: true
  useOtsuThreshold: true
  useSharpen: true
hardware:
  camera:
    ExposureTime: 100000
    AnalogueGain: 5.78
    Brightness: -0.23
    Contrast: 2.06
    Saturation: 1.0
    Sharpness: 1.0
    FrameRate: 60
  gpio:
    LED0: 20
    LED1: 21
    BUZZER: 19
    DI0: 22
    DI1: 27
    DO0: 23
    DO1: 24
    L0: 12
    L1: 23
  rectangle:
    x1: 315
    x2: 634
    y1: 231
    y2: 445
counters:
  ok: 0
  ng: 0
