sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '12356'
  mfg: 01/05/25
  exp: 01/05/27
hardware:
  camera:
    zoom: 100
    focus: 170
    autoFocus: true
    brightness: 184
    contrast: 188
    exposure: 188
    sensorDelay: 500
    saveImage: false
  gpio:
    sensorPin: 23
    buzzerPin: 12
    flashLightPin: 24
  rectangle:
    x1: 440
    x2: 781
    y1: 163
    y2: 350
counters:
  ok: 60
  ng: 5
