sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '51251'
  mfg: 19/09/25
  exp: 19/09/28
system:
  delayShutter: 20
  delayBeforeReject: 500
  rejectionPeriod: 100
  numberStickerBeforeDetection: 4
  rotateImage: 0
  detectionPercentage: 0
  saveImage: false
hardware:
  camera:
    ExposureTime: 27000
    AnalogueGain: 2.93
    Brightness: -0.3
    Contrast: 1.0
    Saturation: 2.6
    Sharpness: 8.0
    FrameRate: 25
  gpio:
    LED0: 20
    LED1: 21
    BUZZER: 19
    DI0: 22
    DI1: 27
    DO0: 23
    DO1: 24
    L0: 12
    L1: 23
  rectangle:
    x1: 260
    x2: 748
    y1: 174
    y2: 517
counters:
  ok: 0
  ng: 0
