sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '51621'
  mfg: 06/09/25
  exp: 06/09/27
system:
  delayShutter: 20
  delayBeforeReject: 500
  rejectionPeriod: 100
  numberStickerBeforeDetection: 4
  rotateImage: 90
  detectionPercentage: 5
  saveImage: false
hardware:
  camera:
    ExposureTime: 10000
    AnalogueGain: 1.68
    Brightness: 0.32
    Contrast: 2.3000000000000003
    Saturation: 1.0
    Sharpness: 4.03
    FrameRate: 25
  gpio:
    LED0: 20
    LED1: 21
    BUZZER: 19
    DI0: 22
    DI1: 27
    DO0: 23
    DO1: 24
    L0: 12
    L1: 23
  rectangle:
    x1: 551
    x2: 867
    y1: 248
    y2: 573
counters:
  ok: 0
  ng: 0
