sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '50756'
  mfg: 19/05/25
  exp: 19/05/27
hardware:
  camera:
    zoom: 100
    focus: 170
    autoFocus: true
    brightness: 184
    contrast: 188
    exposure: 188
    sensorDelay: 500
    saveImage: false
  gpio:
    sensorPin: 23
    buzzerPin: 12
    flashLightPin: 24
  rectangle:
    x1: 330
    x2: 725
    y1: 298
    y2: 524
counters:
  ok: 18
  ng: 18
