sofware:
  name: ระบบตรวจสอบการพิมพ์
  version: 1.0
  debug: false
template:
  lot: '51621'
  mfg: 06/09/25
  exp: 06/09/27
system:
  delayShutter: 100
  delayBeforeReject: 1000
  rejectionPeriod: 100
  numberStickerBeforeDetection: 4
  rotateImage: 90
  detectionPercentage: 20
  saveImage: false
hardware:
  camera:
    ExposureTime: 30000
    AnalogueGain: 1.68
    Brightness: -0.22
    Contrast: 2.3000000000000003
    Saturation: 1.0
    Sharpness: 9.0
    FrameRate: 25
  gpio:
    LED0: 20
    LED1: 21
    BUZZER: 19
    DI0: 22
    DI1: 27
    DO0: 23
    DO1: 24
    L0: 12
    L1: 23
  rectangle:
    x1: 520
    x2: 789
    y1: 257
    y2: 654
counters:
  ok: 0
  ng: 0
